In [9]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)
employee=[]
while True:
  employee.append(Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: ")))
  print("continue : y/n")
  if input()=='n':
    break

print("Number of employees: ",Employee.numberOfEmployees)
avgsalary = averagesalary(employee)
print("Avg salary is :", avgsalary)

Enter name: bhanu teja
Family Members: 5
Employee Salary: 1000
Employee Department: IT
continue : y/n
y
Enter name: vishal
Family Members: 5
Employee Salary: 100000
Employee Department: doctor
continue : y/n
y
Enter name: sathvik
Family Members: 5
Employee Salary: 10000
Employee Department: Analyst
continue : y/n
n
Number of employees:  3
Avg salary is : 37000.0


In [31]:
import numpy as np

randomized_vector = np.random.uniform(1, 20, 20)
print("Randomized_vector",randomized_vector,sep='\n\n',end='\n\n\n')
reshaped_array = randomized_vector.reshape(4, 5)
print("Reshaped_array",reshaped_array,end="\n\n\n\n",sep='\n\n')
reshaped_array[reshaped_array == np.max(reshaped_array, axis=1)[:, None]] = 0
print("Final Array with max value to zero in each row",reshaped_array,sep='\n\n')

Randomized_vector

[ 9.90441793  7.19152918 17.59096874  6.31249572  6.5218349  16.25200521
  5.99826627 14.92959484  7.40120601 10.59880235 19.67723356 13.59299422
 10.97119364 18.29173198  5.79724378 18.58416956  4.16238464 19.7710361
 18.41279219 13.74650471]


Reshaped_array

[[ 9.90441793  7.19152918 17.59096874  6.31249572  6.5218349 ]
 [16.25200521  5.99826627 14.92959484  7.40120601 10.59880235]
 [19.67723356 13.59299422 10.97119364 18.29173198  5.79724378]
 [18.58416956  4.16238464 19.7710361  18.41279219 13.74650471]]



Final Array with max value to zero in each row

[[ 9.90441793  7.19152918  0.          6.31249572  6.5218349 ]
 [ 0.          5.99826627 14.92959484  7.40120601 10.59880235]
 [ 0.         13.59299422 10.97119364 18.29173198  5.79724378]
 [18.58416956  4.16238464  0.         18.41279219 13.74650471]]
